cor_dogs = ['schwarz/braun', 'tricolor', 'schwarz', 'braun', 'schwarz/weiss',
       'weiss', 'weiss/beige', 'schwarz/grau', 'hellbraun/weiss',
       'braun/schwarz', 'beige', 'schwarz/weiss/braun', 'hellbraun',
       'creme', 'silber', 'goldbraun', 'rotbraun', 'gelb',
       'weiss/schwarz', 'weiss/braun', 'mahagoni/weiss', 'golden',
       'black/tan', 'braun/weiss', 'weiss/schwarz/braun', 'saufarben',
       'weiss/grau', 'weiss/blau', 'apricot', 'blue', 'weiss/orange',
       'grau gestromt', 'orange Schimmel', 'rot/beige', 'blue/tan',
       'blondfarben', 'grau/schwarz', 'dunkelbraun', 'rot/grau/schwarz',
       'gestromt', 'graubraun', 'rot/weiss', 'blau',
       'schwarz/braun/weiss', 'braun/beige', 'braun/rot', 'blauschimmel',
       'bianco-aranico', 'schwarz schimmel', 'grau', 'choco',
       'hirschrot mit Maske', 'rot', 'weiss/rot', 'dreifarbig',
       'rot/schwarz', 'grau/braun', 'braun schimmel', 'rotbraun schimmel',
       'red grizzle', 'beige/weiss', 'schwarz/gelb', 'schwarz/beige',
       'rehbraun', 'zobel/weiss', 'schwarz/rot', 'braun gestromt',
       'hirschrot', 'schwarz gestromt', 'brindle', 'beige/rot',
       'gold/sable', 'rot/braun', 'blue/merle', 'beige/schwarz',
       'steelblue/tan', 'steelblue', 'blau/weiss', 'grau/weiss',
       'silber/braun', 'braun schwarz gestromt', 'braun/weiss/schwarz',
       'dunkel gestromt', 'fauve', 'wildfarbig', 'braun/schwarz/weiss',
       'grau meliert', 'pfeffer/salz', 'zimt', 'sable', 'harlekin',
       'weizen', 'blue/steel', 'grau/beige', 'rotbraun/weiss',
       'grau/weiss/schwarz', 'zobel', 'braun meliert', 'löwenfarbig',
       'beige/creme', 'schwarz/weiss/beige', 'rot/grau', 'braun/grau',
       'beige/braun', 'orange', 'red-brindle', 'schwarz/braun/grau',
       'blau/grau/weiss', 'sandfarbig', 'rot/braun/weiss',
       'weiss gestromt', 'weiss/braun/schwarz', 'ruby', 'Harlekin',
       'mahagoni', 'schwarz Marken', 'weiss/schwarz/beige gestromt',
       'gold/schwarz', 'gemischt', 'schwarz/grau/weiss', 'silbergrau',
       'zobel/rot', 'blue merle/weiss', 'beige/braun/schwarz',
       'weiss/creme', 'schwarz/braun gestromt', 'grizzle',
       'beige/grau/weiss', 'schwarz/silber', 'gold/weiss', 'blond/weiss',
       'braun/gold', 'grau/silber', 'schwarz/braun/rot',
       'braun/schwarz/grau', 'weiss/gelb', 'red merle', 'gelb/schwarz',
       'zobel beige', 'schwarz lohfarbig', 'mehrfarbig',
       'grau/braun/schwarz', 'rotblond', 'beige/weiss/braun',
       'red-wheaten', 'schwarz/beige/grau', 'marronschimmel',
       'hellfarben', 'hell-/dunkelbraun', 'fawn', 'gelb/weiss',
       'grau/weiss/beige', 'grau/braun/weiss', 'haarlos',
       'schwarz/braun/beige', 'wheaton', 'grau/weiss/braun', 'beige/grau',
       'braun/weiss/beige', 'gelb/braun', 'schwarz/loh', 'blau/grau',
       'vierfarbig', 'beige gestromt', 'schwarz/gold', 'braun/rot/weiss',
       'blue-brindle', 'schwarz melliert', 'bicolor']


rasse_dogs = ['Welsh Terrier', 'Berner Sennenhund', 'Mischling gross',
       'Labrador Retriever', 'Mittelschnauzer', 'Shih Tzu', 'Dackel',
       'Bichon frisé', 'Lagotto Romagnolo', 'Zwergdackel', 'Havaneser',
       'Bergamasker', 'Border Collie', 'Pinscher', 'Chihuahua',
       'Golden Retriever', 'Mischling klein', 'Weimaraner',
       'Tibetan Spaniel', 'Leonberger', 'Shiba Inu', 'Beagle',
       'Border Terrier', 'Magyar Viszla', 'Französische Bulldogge',
       'Jack Russel Terrier', 'Cocker Spaniel', 'Pointer', 'Mops',
       'Staffordshire Bull Terrier', 'Grosspudel', 'Lhasa Apso',
       'Englische Bulldogge', 'English Springer Spaniel',
       'Langhaardackel', 'Zwergdachshund', 'Zwergpinscher',
       'Biewer Yorkshire Terrier', 'Parson Jack Russell Terrier',
       'Malteser', 'Husky', 'Zwergspitz', 'Bolonka Zwetna',
       'Neufundländer', 'Spitz', 'Parson Russell Terrier', 'Terrier',
       'Berger blanc Suisse', 'Zwergpudel', 'Foxterrier', 'Kooiker',
       'Mittelpudel', 'Cairn Terrier', 'Yorkshire Terrier', 'Boxer',
       'Pudel', 'Labradoodle', 'Dobermann', 'Deutscher Schäfer', 'Mudi',
       'Papillon', 'Dachshund', 'Italienisches Windspiel',
       'Holländischer Schäfer', 'Welsh Springer Spaniel',
       'Deutsche Dogge', 'Coton de Tulear', 'Hovawart',
       'English Cocker Spaniel', 'Hirtenhund',
       'Soft Coated Wheaten Terrier', 'Prager Rattler', 'Canaan Dog',
       'Bouvier', 'Jura Laufhund', 'Spanischer Wasserhund',
       'Bayerischer Gebirgsschweisshund', 'American Bulldog',
       'Appenzeller', 'Beauceron Berge de Beauce', 'Beauceron',
       'Bichon Havanais', 'Windspiel', 'Irish Setter', 'Bearded Collie',
       'Bichon', 'Deutscher Wachtel', 'Rottweiler',
       'Schweizer Niederlaufhund', 'West Highland White Terrier',
       'Irish Terrier', 'Tervueren', 'Belgischer Schäfer', 'Groenendael',
       'Toypudel', 'Podenco', 'Parson Terrier', 'Basset Griffon vendéen',
       'Rauhaar Dackel', 'Epagneul Breton', 'Appenzeller Sennenhund',
       'Dalmatiner', 'Nova Scotia Duck Tolling Retriever',
       'Galgo Español', 'Deutscher Boxer', 'Rhodesian Ridgeback',
       'Riesenschnauzer', 'Spinone', 'Scottish Terrier',
       'Zwergrauhaardackel', 'Phalène', 'Australian Shepherd',
       'Mittelspitz', 'Airedale Terrier', 'Collie',
       'Miniature Bull Terrier', 'Tibet Terrier',
       'Alpenländische Dachsbracke', 'Sheltie', 'Greyhound', 'Bobtail',
       'Katalanischer Hirtenhund', 'Spaniel', 'Schweizer Sennenhund',
       'Afghane', 'Zwergschnauzer', 'Berger Picard', 'Sennenhund',
       'Pekingese', 'Chinese Crested Powderpuff',
       'Portugiesischer Wasserhund', 'Deutscher Pinscher',
       'Altdeutscher Schäfer', 'Whippet', 'Münsterländer',
       'Kleiner Münsterländer', 'Azawakh', 'Chinese Crested',
       'Miniature Australien Shepard', 'Flat Coated Retriever',
       'Chow Chow', 'Irish Soft Coated Wheaten Terrier',
       'Entlebucher Sennenhund', 'Islandhund', 'Rehpinscher',
       'Fila Brasileiro', 'Schäfer', 'Bulldog', 'Kromfohrländer',
       'Setter', 'Griffon', 'Norwich Terrier', 'Continental Bulldog',
       'Briard', "Gos d'Atura Català", 'English Setter',
       'Cavalier King Charles Spaniel', 'Sibirischer Husky', 'Samojede',
       'Eurasier', 'Schnauzer', 'Vizsla', 'Foo Dog gross', 'Entlebucher',
       'Volpino', 'Dogge', 'Basenji', 'Toy Pudel', 'Toyterrier',
       'Welsh Corgi Cardigan', 'Akita Inu', "Cirneco dell'Etna",
       'Königspudel', 'Bordeaux Dogge', 'Powder Puff',
       'Petit Basset Griffon', 'Deutscher Langhaarschäfer',
       'Goldendoodle', 'Irish Wolfhound', 'Skye Terrier', 'Galgo',
       'Vorstehhund', 'Afghanischer Windhund', 'Deerhound', 'Dachsbracke',
       'American Cocker Spaniel', 'Breton', 'Windhund',
       'King Charles Spaniel', 'Gordon Setter', 'Cane Corso',
       'Russischer Terrier', 'Berger des Pyrenées', 'Bernhardiner',
       'American Staffordshire Terrier', 'Welsh Corgi', 'Boston Terrier',
       'Segugio', 'Alaskan Malamute', 'Mastiff', 'Basset Hound',
       'Japan Chin', 'Polski Owczarek Nizinny', 'Kleinspitz',
       'Altdeutscher Hütehund', 'Podenco Ibicenco', 'Jagdhund',
       'Cattle Dog', 'Toller', 'Field Spaniel', 'Schapendoes',
       'Dogo Canario', 'Australian Terrier', 'Anatolischer Hirtenhund',
       'Spanischer Windhund', 'Berger de Brie', 'Thai Ridgeback',
       'Maremma-Abruzzenhund', 'Australian Cattle Dog', 'Pomeranian',
       'Lakeland Terrier', 'Schwedischer Vallhund', 'Shetland Sheepdog',
       'Manchester Terrier', 'Poitevin Jagdhund', 'Norfolk Terrier',
       'Kaninchen-Dachshund', 'Daisy-Dog', 'Barbet', 'Shar Pei', 'Pumi',
       'Maremmano', 'Katalanischer Schäferhund', 'Bardino',
       'English Staffordshire Terrier', 'Malinois', 'Do-Khyi',
       'Saarloos-Wolfshund', 'Old Englische Bulldogge',
       'Deutsch Drahthaar', 'Welsh Corgi Pembroke', 'Saluki',
       'Chesapeake Bay Retriever', 'Pit Bull Terrier', 'Bichon maltais',
       'Chinese Crested Hairless Dog', 'Tiroler Bracke',
       'Irish Water Spaniel', 'Tschechoslowakischer Wolfshund',
       'Bologneser', 'Silky Terrier', 'Perro Dogo Mallorquin', 'Löwchen',
       'Dogo Argentino', 'Deutscher Jagdterrier', 'Niederlaufhund',
       'Landseer', 'Kerry Blue Terrier', 'Affenpinscher',
       'Slovensky Cuvac', 'Elo', 'Deutscher Grossspitz', 'Retriever',
       'Border', 'Berger de Beauce', 'Deutscher Kurzhaar',
       'Perro de Agua', 'Chodsky pes', 'Harzer Fuchs', 'Ratero',
       'Curly Coated Retriever', 'English Toy Terrier', 'Chinese Foo Dog',
       'Kurzhaar Dackel', 'Teckel', 'Alano', 'Wasserhund', 'Puli',
       'Kuvasz', 'Bretonischer Spaniel', 'Norwegischer Buhund',
       'Norwegischer Lundehund', 'Finnischer Lapphund',
       'Cimarron Uruguayo', 'Pyrenäen', 'Sloughi', 'Russkiy Toy',
       'Polnische Bracke', 'Bull Terrier', 'Transylvanischer Laufhund',
       'Nackthund', 'Australien Kelpie', 'Chinese Powder Puff', 'Malamut',
       'Deutscher Vorstehhund', 'Wolfspitz', 'Wäller', 'Kangal',
       'Boerboel', 'Luzerner Laufhund', 'Corgie', 'Ratenero Bodeguero',
       'Kishu', 'Laufhund']

rassentyp = ['K', 'I', 'II'] 